# ~/.ticker.yaml
show-summary: true
# show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
# currency: USD
currency-summary-only: false
sort: value
watchlist:
  - btc-usd
  - eth-usd
  # - lha.de
  # - alv.de
  - bayn.de
  # - xiacf
  # - spce
  - pltr
  # - sofi
  - b4b.de
  - ibm
  # - intc
  - msft
  - amd
  - t
  - vz
  - ibe1.de
  - fb
  - pypl
  - u
  - qs
  - cat
  - tte.pa
  - lin.de
  # - bas.de
  - hen3.de
lots:
  - symbol: "LHA.DE"
    quantity: 3300
    unit_cost: 5.92
  - symbol: "ALV.DE"
    quantity: 60
    unit_cost: 158.21
  - symbol: "BAS.DE"
    quantity: 1300.0
    unit_cost: 46.74
  - symbol: "XIACF"
    quantity: 1050
    unit_cost: 1.27
  - symbol: "SPCE"
    quantity: 1400
    unit_cost: 12.33
  - symbol: "SOFI"
    quantity: 1000
    unit_cost: 10.50
  - symbol: "INTC"
    quantity: 500
    unit_cost: 30.07
  - symbol: "MO"
    quantity: 500
    unit_cost: 40.1
# colors:
#   text: "#005fff"
#   text-light: "#0087ff"
#   text-label: "#00d7ff"
#   text-line: "#00ffff"
#   text-tag: "#005fff"
#   background-tag: "#0087ff"

