# zlozi prazdny riadok medzi prompt
add_newline = true

# zmena prompt formatu
format = """\
[╭╴](240)$env_var\
$all[╰─](240)$character"""

# zmena prompt symbolu
[character]
success_symbol = "[](240)"
error_symbol = "[](240)"

# zobrazi ikonu OS
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'
variable = "STARSHIP_DISTRO"
disabled = false

# zobrazenie cesty priecinkov
[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

# zmena python ikony
[python]
symbol = " "
python_binary = "python3"

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "
