# [line_break]
# disabled = false

# zmena prompt formatu
format = """\
[╭╴](white)$env_var\
$all[╰─](white)$character"""

# zmena prompt symbolu
[character]
success_symbol = "[ ➜](240)"
error_symbol = "[ ➜](red)"

# zobrazi ikonu OS
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold)'
variable = "STARSHIP_DISTRO"
disabled = false

[directory]
# truncation_length = 3
# truncation_symbol = "…/"
style = "cyan"
home_symbol = "  ~"
read_only_style = "red"
read_only = "  "
format = "[$read_only]($read_only_style)[$path]($style) "
# format = "[$path]($style)[$read_only]($read_only_style) "

# SYMBOLS
[python]
symbol = " "

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "
