# zlozi prazdny riadok medzi prompt
# add_newline = true

# zmena prompt formatu
format = """\
[╭╴](240)$env_var\
$all[╰─](240)$character"""

# zmena prompt symbolu
[character]
success_symbol = "[❯](240)"
error_symbol = "[❯](red)"

# zobrazi ikonu OS
[env_var.STARSHIP_DISTRO]
format = "[$env_value](bold white)"
variable = "STARSHIP_DISTRO"
disabled = false

[directory]
# truncation_length = 3
# truncation_symbol = "…/"
style = "cyan"
home_symbol = "  ~"
read_only_style = "197"
read_only = " "
format = "[$read_only]($read_only_style)[$path]($style) "

# SYMBOLS
[python]
symbol = " "
# python_binary = "python3"

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "
