# zlozi prazdny riadok medzi prompt
add_newline = true

# zmena prompt formatu
# format = """\
# [╭╴](240)$env_var\
# $all[╰─](240)$character"""

format = """\
[╭╴](#727169)$os\
$all[╰──](#727169)$character"""

# zmena prompt symbolu
[character]
success_symbol = "[❯](#727169)"
error_symbol = "[❯](red)"

# zobrazi ikonu OS - stare riesenie
# [env_var.STARSHIP_DISTRO]
# format = "[$env_value](bold white)"
# variable = "STARSHIP_DISTRO"
# disabled = false

[os]
format = '[$symbol]($style)'
style = "white"
disabled = false

[os.symbols]
Windows = "  "
openSUSE = "  "

[directory]
# truncation_length = 3
# truncation_symbol = "…/"
style = "cyan"
home_symbol = "  ~"
read_only_style = "197"
read_only = " "
format = "[$read_only]($read_only_style)[$path]($style) "

# SYMBOLS
[python]
symbol = " "
# python_binary = "python3"

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "
