# zmena prompt formatu
format = """\
[╭╴](gray)$env_var\
$all[╰─](gray)$character"""

# zmena prompt symbolu
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# zobrazi ikonu OS
[env_var.STARSHIP_DISTRO]
format = "[$env_value](bold gray)"
variable = "STARSHIP_DISTRO"
disabled = false

[directory]
# truncation_length = 3
# truncation_symbol = "…/"
style = "cyan"
home_symbol = "  ~"
read_only_style = "red"
read_only = " "
format = "[$read_only]($read_only_style)[$path]($style) "

# SYMBOLS
[python]
symbol = " "

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "
