[colors]
ansi = [
    "#090618",
    "#c34043",
    "#76946a",
    "#c0a36e",
    "#7e9cd8",
    "#957fb8",
    "#6a9589",
    "#1f1f28",
    ]
brights = [
    "#727169",
    "#e82424",
    "#98bb6c",
    "#e6c384",
    "#7fb4ca",
    "#938aa9",
    "#7aa89f",
    "#c8c093",
    ]

background = "#fefefa"
foreground = "#1f1f28"
cursor_bg = "#1f1f28"
cursor_border = "#1f1f28"
cursor_fg = "#fefefa"

selection_bg = "#2d4f67"
selection_fg = "#fefefa"
scrollbar_thumb = "#16161d"
split = "#16161d"

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d62"

[metadata]
name = "kanagawa-light"
